FROM ubuntu

# docker build -t ghcr.io/converged-computing/metric-hello-world .
# The entrypoint to download the pid wait command will be generated on the fly
# via a config map

RUN apt-get update && apt-get install -y git g++ build-essential wget
