FROM ubuntu

# docker build -t ghcr.io/converged-computing/metric-fio .
# https://docs.gitlab.com/ee/administration/operations/filesystem_benchmarking.html

RUN apt-get update && apt-get install -y git g++ build-essential wget fio
